os: osx
# https://docs.travis-ci.com/user/languages/objective-c#supported-xcode-versions
osx_image: xcode12.2

before_install:
  - brew install git-lfs
  - git-lfs install --system

script:
  - source setup.env && just test
  - just test int git_mirror
  - just test int just_install_functions
