os: osx
# https://docs.travis-ci.com/user/languages/objective-c#supported-xcode-versions
osx_image: xcode12.5

before_install:
  - brew install git-lfs
  - git-lfs install --system

script:
  - source setup.env && just test
  - just test int git_mirror just_install_functions

# We only want travis to run on PRs, master, and branches with "travisci" in
# the name. This will help limit the limited builds
branches:
  only:
  - master
  - /^.*(?i:travisci).*$/