#!/usr/bin/env bash

function findinpaths()
{
  base_name="$1"
  shift 1
  for d in "${@}"; do
    if [ -e "${d}/${base_name}" ]; then
      echo "${d}/${base_name}"
    fi
  done
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  findinpaths "${@}"
  exit $?
fi