#!/usr/bin/env bash

source_once &> /dev/null && return

#*# linux/findin

#**
# =======
# Find In
# =======
#
# .. default-domain:: bash
#
# .. file:: findin
#
# :Arguments: * ``$1`` - Value to search for
#             * [``$2``...] - Values of array to search over
# :Output: *stdout* - ``-1`` for not found, else the index of the first match
#
# ``Bash`` CLI version of findin
#
# .. seealso::
#   :func:`findin`
#**

#**
# .. function:: findin
#
# :Arguments: * ``$1`` - Value to search for
#             * [``$2``...] - Values of array to search over
# :Output: *stdout* - ``-1`` for not found, else the index of the first match
#
# Finds the index of the first match in an array
#
# .. rubric:: Examplie
#
# .. code-block:: bash
#
#   findin 33 11 22 33 44
#   # 2
#   findin 0 2 2 2
#   # -1
#**
function findin()
{
  local x
  local val=$1
  shift 1
  local args=(${@+"${@}"})
  for x in "${!args[@]}"; do
    if [ "${args[$x]}" == "${val}" ]; then
      echo "$x"
      return
    fi
  done
  echo -1
}

if [[ ${BASH_SOURCE[0]} == ${0} ]] || [[ $(basename "${BASH_SOURCE[0]}") == ${0} ]]; then
  findin "${@}"
  exit $?
fi