#!/usr/bin/env bash

# Check if arg 1 is in the rest of the argument list

function findin()
{
  local x
  local val=$1
  shift 1
  local args=(${@+"${@}"})
  for x in "${!args[@]}"; do
    if [ "${args[$x]}" == "${val}" ]; then
      echo $x
      return
    fi
  done
  echo -1
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  findin "${@}"
  exit $?
fi