#!/usr/bin/env bash

source_once >&/dev/null && return

#*# linux/findinpaths

#**
# =============
# Find In Paths
# =============
#
# .. default-domain:: bash
#
# .. file:: findinpaths
#
# :Arguments: * ``$1`` - filename to search for
#             * [``$2``...] - Array of paths
# :Output: *stdout* - Full path of files found in all the paths
#
# ``Bash`` CLI version of findinpaths
#
# .. seealso::
#   :func:`findinpaths`
#**

#**
# .. function:: findinpaths
#
# :Arguments: * ``$1`` - filename to search for
#             * [``$2``...] - Array of paths
# :Output: *stdout* - Full path of files found in all the paths
#
# Searches an array of paths, looking for a file
#
# .. rubric:: Example
#
# .. code-block:: bash
#
#   findinpaths ls /bin /usr/bin /usr/local/bin
#   # /bin/ls
#**
function findinpaths()
{
  base_name="$1"
  shift 1
  for d in "${@}"; do
    if [ -e "${d}/${base_name}" ]; then
      echo "${d}/${base_name}"
    fi
  done
}

if [[ ${BASH_SOURCE[0]} == ${0} ]] || [[ $(basename "${BASH_SOURCE[0]}") == ${0} ]]; then
  findinpaths "${@}"
  exit $?
fi