#!/usr/bin/env bash

#*# linux/git_commit_description

#**
# ======================
# Git Commit Description
# ======================
#
# .. default-domain:: bash
#
# .. file:: git_commit_description
#
# :Output: *stdout* - The preferred ``git describe`` output
#
# Helper script for printing out the preferred ``git describe`` for a repo
#**

git describe --all --long --always --dirty
