#!/usr/bin/env bash

# Helper file for submodule update in just_git_functions

set -eu

# Retrieve the SHA (Some versions of git and git server don't support or allow
# fetching a single SHA). This is really only necessary if just_upstream's URL
# changes during sync because a git fetch in the parent repository will fetch
# changes in the submodules as well (assuming fetch.recurseSubmodules is
# enabled, which it is by default since at least git 1.8.3)
# git submodule update also fetches when needed by default, but it also fetches
# on origin
git fetch "${JUST_GIT_USE_REMOTE-${JUST_GIT_UPSTREAM-just_upstream}}" "${1}" || \
    git fetch "${JUST_GIT_USE_REMOTE-${JUST_GIT_UPSTREAM-just_upstream}}"
# Store the branch name in case merge fails; this will reattach the head
# exactly how it was
before_branch="$(git rev-parse --abbrev-ref HEAD)"
# Detach the head
git checkout "$(git rev-parse HEAD)" &> /dev/null
rv=0
# Cannot checkout FETCH_HEAD when git fails to fetch a single SHA (see above)
git merge --ff-only "${1}" || rv=${?}
if [ "${rv}" != "0" ]; then
  git checkout "${before_branch}"
  exit "${rv}"
fi