#!/usr/bin/env bash

set -eu

# Retrieve the sha
git fetch "${JUST_GIT_USE_REMOTE-${JUST_GIT_UPSTREAM-just_upstream}}" "${1}"
# store the branch name incase merge fails, this will reattach the head how
# exactly it was
before_branch="$(git rev-parse --abbrev-ref HEAD)"
# detach the head
git checkout "$(git rev-parse HEAD)"
rv=0
git merge --ff-only FETCH_HEAD || rv=$?
if [ "${rv}" != "0" ]; then
  git checkout "${before_branch}"
  exit "${rv}"
fi