#!/usr/bin/env bash

#*# linux/git_commit_description

#**
# ======================
# Git Commit Description
# ======================
#
# .. default-domain:: bash
#
# .. file:: git_commit_description
#
# :Output: *stdout* - The preferred ``git describe`` output
#
# Helper script for printing out the preferred ``git describe`` for a repo
#**

function git_commit_description()
{
  git describe --all --long --always --dirty
}

if [ "${BASH_SOURCE[0]}" = "${0}" ] || [ "$(basename "${BASH_SOURCE[0]}")" = "${0}" ]; then
  git_commit_description ${@+"${@}"}
  exit "${?}"
fi