#!/usr/bin/env bash

# Helper file for submodule update in just_git_functions

set -eu

# Retrieve the SHA
git fetch "${JUST_GIT_USE_REMOTE-${JUST_GIT_UPSTREAM-just_upstream}}" "${1}"
# Store the branch name in case merge fails; this will reattach the head
# exactly how it was
before_branch="$(git rev-parse --abbrev-ref HEAD)"
# Detach the head
git checkout "$(git rev-parse HEAD)"
rv=0
git merge --ff-only FETCH_HEAD || rv=$?
if [ "${rv}" != "0" ]; then
  git checkout "${before_branch}"
  exit "${rv}"
fi