#!/usr/bin/env bash

if [[ ${-} != *i* ]]; then
  source_once &> /dev/null && return 0
fi

#*# linux/inisin

#**
# ========
# In Is In
# ========
#
# .. default-domain:: bash
#
# .. file:: inisin
#
# :Arguments: * ``$1`` - Value to search for
#             * [``$2``...] - Values of array to search over
# :Output: Exit code is ``0`` for found, ``1`` for not found
#
# Bash CLI version of :func:`inisin`
#
# .. seealso::
#   :func:`inisin`
#**

#**
# .. function:: inisin
#
# :Arguments: * ``$1`` - Value to search for (can be regex)
#             * [``$2``...] - Values of array to search over
# :Output: Returns ``0`` for found, ``1`` for not found
#
# Checks if any string in the array contains a regex/substring
#
# .. rubric:: Example
#
# .. code-block:: bash
#
#   inisin 3 11 22 33 44
#   # $? is 0
#   inisin 1 20 20 20
#   # $? is 1
#**
function inisin()
{
  local val
  local x

  val="${1}"
  shift 1
  for x in ${@+"${@}"}; do
    if [[ ${x} =~ ${val} ]]; then
      return 0
    fi
  done
  return 1
}

if [ "${BASH_SOURCE[0]}" = "${0}" ] || [ "$(basename "${BASH_SOURCE[0]}")" = "${0}" ]; then
  inisin "${@}"
  exit $?
fi