#!/usr/bin/env bash

# Check if arg 1 is in the rest of the argument list

function isin()
{
  local val
  local x

  val=$1
  shift 1
  for x in "${@}"; do
    if [ "${x}" == "${val}" ]; then
      return 0
    fi
  done
  return 1
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  isin "${@}"
  exit $?
fi