#!/usr/bin/env bash

source_once &> /dev/null && return

#*# linux/isin

#**
# =====
# Is In
# =====
#
# .. default-domain:: bash
#
# .. file:: isin
#
# :Arguments: * ``$1`` - Value to search for
#             * [``$2``...] - Values of array to search over
# :Output: Exit code is ``0`` for found, ``1`` for not found
#
# ``Bash`` CLI version of isin
#
# .. seealso::
#   :func:`isin`
#**

#**
# .. function:: isin
#
# :Arguments: * ``$1`` - Value to search for
#             * [``$2``...] - Values of array to search over
# :Output: Returns ``0`` for found, ``1`` for not found
#
# Checks if a value is in an array
#
# .. rubric:: Example
#
# .. code-block:: bash
#
#   isin 33 11 22 33 44
#   # $? is 0
#   isin 0 2 2 2
#   # $? is 1
#**
function isin()
{
  local val
  local x

  val=$1
  shift 1
  for x in ${@+"${@}"}; do
    if [ "${x}" == "${val}" ]; then
      return 0
    fi
  done
  return 1
}

if [[ ${BASH_SOURCE[0]} == ${0} ]] || [[ $(basename "${BASH_SOURCE[0]}") == ${0} ]]; then
  isin "${@}"
  exit $?
fi