#!/usr/bin/env bash

#****F* vsi/isin
# NAME
#   isin - Bash CLI version of isin
# INPUTS
#   $1 - Value to search for
#   [$2...] - Values of array to search over
# OUTPUT
#   Exit code is 0 for found, 1 for not found
# SEE ALSO
#   isin/isin
#***

#****f* isin/isin
# NAME
#   isin - Checks if a value is in an array
# INPUTS
#   $1 - Value to search for
#   [$2...] - Values of array to search over
# OUTPUT
#   Returns 0 for found, 1 for not found
# EXAMPLE
#   isin 33 11 22 33 44
#   # $? is 0
#   isin 0 2 2 2
#   # $? is 1
# AUTHOR
#   Andy Neff
#***
function isin()
{
  local val
  local x

  val=$1
  shift 1
  for x in ${@+"${@}"}; do
    if [ "${x}" == "${val}" ]; then
      return 0
    fi
  done
  return 1
}

if [[ ${BASH_SOURCE[0]} == ${0} ]] || [[ $(basename ${BASH_SOURCE[0]}) == ${0} ]]; then
  isin "${@}"
  exit $?
fi