#!/usr/bin/env bash

#*# linux/postisin

#**
# ========
# Postisin
# ========
#
# .. default-domain:: bash
#
# .. file:: postisin
#
#**
##****F* vsi/postisin
# NAME
#   postisin - Bash CLI version of postisin
# INPUTS
#   $1 - Value to search for
#   [$2...] - Values of array to search over
# OUTPUT
#   Exit code is 0 for found, 1 for not found
# SEE ALSO
#   postisin/postisin
##***

##****f* postisin/postisin
# NAME
#   postisin - Checks if any element in the array ends with a value
# INPUTS
#   $1 - Value to search for (can be regex)
#   [$2...] - Values of array to search over
# OUTPUT
#   Returns 0 for found, 1 for not found
# EXAMPLE
#   postisin 3 11 22 33 44
#   # $? is 0
#   postisin 0 02 02 02
#   # $? is 1
# AUTHOR
#   Andy Neff
##***
function postisin()
{
  local val
  local x

  val=$1
  shift 1
  for x in ${@+"${@}"}; do
    if [[ ${x} =~ ${val}$ ]]; then
      return 0
    fi
  done
  return 1
}

if [[ ${BASH_SOURCE[0]} == ${0} ]] || [[ $(basename "${BASH_SOURCE[0]}") == ${0} ]]; then
  postisin "${@}"
  exit $?
fi