#!/usr/bin/env bash

if [[ ${-} != *i* ]]; then
  source_once &> /dev/null && return 0
fi

function precommit::filter_line()
{
  local commit_message
  if [ "${2}" != 0000000000000000000000000000000000000000 ]; then
    commit_message=$(git log --format=%s -n 1 ${2})
  fi
  if [[ ${commit_message} =~ \[skip\ ci\] ]] || [[ ${commit_message} =~ \[ci\ skip\] ]]; then
    return
  fi
  echo "${@}"
}
function precommit::filter_lines()
{
  while read -r line || [[ -n "${line}" ]]; do
    precommit::filter_line ${line} # no quotes
  done < <(cat -)
}

if [ "${BASH_SOURCE[0]}" = "${0}" ] || [ "$(basename "${BASH_SOURCE[0]}")" = "${0}" ]; then
  precommit::filter_lines "${@}"
  exit "${?}"
fi
