#!/usr/bin/env bash

if [[ $- != *i* ]]; then
  source_once &> /dev/null && return 0
fi

#*# linux/preisin

#**
# =======
# Preisin
# =======
#
# .. default-domain:: bash
#
# .. file:: preisin
#
# :Arguments: * ``$1`` - Value to search for
#             * [``$2``...] - Values of array to search over
# :Output: Exit code is ``0`` for found, ``1`` for not found
#
# ``Bash`` CLI version of preisin
#
# .. seealso::
#   :func:`preisin`
#**

#**
# .. function:: preisin
#
# :Arguments: * ``$1`` - Value to search for (can be regex)
#             * [``$2``...] - Values of array to search over
# :Output: Returns ``0`` for found, ``1`` for not found
#
# Checks if any element in the array starts with a value
#
# .. rubric:: Example
#
# .. code-block:: bash
#
#   preisin 3 11 22 33 44
#   # $? is 0
#   preisin 0 20 20 20
#   # $? is 1
#**
function preisin()
{
  local val
  local x

  val=$1
  shift 1
  for x in ${@+"${@}"}; do
    if [[ ${x} =~ ^${val} ]]; then
      return 0
    fi
  done
  return 1
}

if [ "${BASH_SOURCE[0]}" = "${0}" ] || [ "$(basename "${BASH_SOURCE[0]}")" = "${0}" ]; then
  preisin "${@}"
  exit $?
fi