#!/usr/bin/env bash

##****F* vsi/preisin
# NAME
#   preisin - Bash CLI version of preisin
# INPUTS
#   $1 - Value to search for
#   [$2...] - Values of array to search over
# OUTPUT
#   Exit code is 0 for found, 1 for not found
# SEE ALSO
#   preisin/preisin
##***

##****f* preisin/preisin
# NAME
#   preisin - Checks if any element in the array starts with a value
# INPUTS
#   $1 - Value to search for (can be regex)
#   [$2...] - Values of array to search over
# OUTPUT
#   Returns 0 for found, 1 for not found
# EXAMPLE
#   preisin 3 11 22 33 44
#   # $? is 0
#   preisin 0 20 20 20
#   # $? is 1
# AUTHOR
#   Andy Neff
##***
function preisin()
{
  local val
  local x

  val=$1
  shift 1
  for x in ${@+"${@}"}; do
    if [[ ${x} =~ ^${val} ]]; then
      return 0
    fi
  done
  return 1
}

if [[ ${BASH_SOURCE[0]} == ${0} ]] || [[ $(basename ${BASH_SOURCE[0]}) == ${0} ]]; then
  preisin "${@}"
  exit $?
fi