#!/usr/bin/env bash

function real_path_manual()
{ #Mainly for Darwin
  cd "$(dirname "$1")"
  local target="$(basename "$1")"

  while [ -L "$target" ]
  do
    target="$(readlink "$target")"
    cd "$(dirname "$target")"
    target="$(basename "$target")"
  done

  local physical_dir="$(pwd -P)"

  if [ "${physical_dir}" == "/" ]; then
    echo /$target
  else
    echo ${physical_dir}/$target
  fi
}

if ! cmd=$(command -v realpath); then
  cmd="readlink -f"
  if ! ${cmd} / > /dev/null 2>&1; then
    #Probably Darwin. Thanks Darwin! > : (
    for x in "${@}"; do
      real_path_manual "${x}"
    done
    exit 0
  fi
fi

exec $cmd "${@}"
