#!/usr/bin/env bash

if [[ ${-} != *i* ]]; then
  source_once &> /dev/null && return 0
fi

#*# linux/reisin

#**
# ========================
# Regular Expression Is In
# ========================
#
# .. default-domain:: bash
#
# .. file:: reisin
#
# :Arguments: * ``$1`` - Regex to search for
#             * [``$2``...] - Values of array to search over
# :Output: Exit code is ``0`` for found, ``1`` for not found
#
# Bash CLI version of :func:`reisin`
#
# .. seealso::
#   :func:`reisin`
#**

#**
# .. function:: reisin
#
# :Arguments: * ``$1`` - Regex to search for
#             * [``$2``...] - Values of array to search over
# :Output: Returns ``0`` for found, ``1`` for not found
#
# Checks if any string in the array matches a regex
#
# .. rubric:: Example
#
# .. code-block:: bash
#
#   reisin '[35]' 11 22 33 44
#   # $? is 0
#   reisin '^.*1.*$' 20 20 20
#   # $? is 1
#**
function reisin()
{
  local val
  local x

  val="${1}"
  shift 1
  for x in ${@+"${@}"}; do
    if [[ ${x} =~ ${val} ]]; then
      return 0
    fi
  done
  return 1
}

if [ "${BASH_SOURCE[0]}" = "${0}" ] || [ "$(basename "${BASH_SOURCE[0]}")" = "${0}" ]; then
  reisin "${@}"
  exit "${?}"
fi