name: macOS tests

# This is required
on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  just-test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          source setup.env
          just test
      - run: |
          source setup.env
          just test int git_mirror just_install_functions
