name: macOS tests

# This is required
on:
  push:

jobs:
  just-test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Unit tests
        run: |
          source setup.env
          just --help || :
          bash -xv just test
      - name: Integration tests
        run: |
          source setup.env
          just test int git_mirror just_install_functions
