name: macOS tests

# This is required
on:
  push:

jobs:
  just-test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fix git breaking on purpose
        run: |
          printf '=%.0s' {1..1000}
          git config --global --add safe.directory '*'
          git config --global protocol.file.allow always

      - name: Unit tests
        run: |
          source setup.env
          just test
      - name: Integration tests
        run: |
          source setup.env
          just test int git_mirror just_install_functions
