name: macOS tests

# Try and limit the CI runs, since we only get 200 minutes per month
on: 
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  just-test:
    runs-on: macos-11
    steps:
      - run: pwd
      - run: echo "${{ github.workspace }}"
      - run: ls -la
      - run: source setup.env
      - run: just test
      - run: just test int git_mirror just_install_functions